/* ═══════════════════════════════════════════════════════════════════════
   corpus.js — banque de questions et scènes-photos

   Corpus original, écrit pour ce projet (pas de contenu d'un examinateur
   ou d'un site tiers copié). Il couvre les 9 thèmes officiels de la partie
   expression orale A2 du Sproochentest (INLL) : présentation, famille,
   travail, logement, transports, loisirs, santé, nourriture, Luxembourg,
   projets. ~70 questions pour démarrer sérieusement — pas 278 : mieux vaut
   un socle correct et vérifiable qu'un grand nombre de phrases inventées.
   Le format est fait pour grandir : ajoute des objets dans QUESTIONS,
   rien d'autre à toucher.

   ⚠️ Le luxembourgeois ci-dessous vise le niveau A2 courant, mais n'a
   pas été relu par un locuteur natif. Fais-le relire avant de t'y fier
   à 100 % pour un examen réel — surtout la grammaire (cas, position du
   verbe) qui varie vite d'une phrase à l'autre.
   ═══════════════════════════════════════════════════════════════════════ */
(function(global){

const CATS = [
  {id:'virstellung', lb:'Virstellung',  fr:'Présentation'},
  {id:'famill',       lb:'Famill',       fr:'Famille'},
  {id:'aarbecht',     lb:'Aarbecht',     fr:'Travail'},
  {id:'wunnen',       lb:'Wunnen',       fr:'Logement'},
  {id:'transport',    lb:'Transport',    fr:'Transports'},
  {id:'fraizeit',     lb:'Fräizäit',     fr:'Loisirs'},
  {id:'gesondheet',   lb:'Gesondheet',   fr:'Santé'},
  {id:'iessen',       lb:'Iessen',       fr:'Nourriture'},
  {id:'letzebuerg',   lb:'Lëtzebuerg',   fr:'Luxembourg'},
  {id:'plaeng',       lb:'Pläng',        fr:'Projets'},
];

// id · cat · lb (question) · fr · model_lb (réponse modèle) · model_fr ·
// grond (pourquoi cette forme, en un point) · vocab[] · pitfall (erreur fréquente)
const QUESTIONS = [
// ── Virstellung ─────────────────────────────────────────────────────────
{id:'q001', cat:'virstellung', lb:'Wéi heescht Dir?', fr:'Comment vous appelez-vous ?',
  model_lb:'Ech heesche Sara, ech kommen aus Frankräich a wunnen zanter dräi Joer zu Lëtzebuerg.',
  model_fr:'Je m’appelle Sara, je viens de France et j’habite au Luxembourg depuis trois ans.',
  grond:'Une réponse complète donne le nom, l’origine et la durée — pas juste le prénom.',
  vocab:['heeschen (s’appeler)','kommen aus (venir de)','zanter (depuis)'], pitfall:'Répondre seulement par le prénom, sans phrase.'},
{id:'q002', cat:'virstellung', lb:'Wéi al sidd Dir?', fr:'Quel âge avez-vous ?',
  model_lb:'Ech sinn siwenzeg... nee, ech sinn drësseg Joer al.',
  model_fr:'J’ai trente ans.',
  grond:'En luxembourgeois l’âge se dit avec sinn + Joer al, pas avec « avoir ».',
  vocab:['al sinn (avoir … ans)','Joer (année)'], pitfall:'Traduire mot à mot « j’ai » par « hunn ».'},
{id:'q003', cat:'virstellung', lb:'Wat ass Är Mammesprooch?', fr:'Quelle est votre langue maternelle ?',
  model_lb:'Meng Mammesprooch ass Portugisesch, mä ech schwätzen och Franséisch a Lëtzebuergesch.',
  model_fr:'Ma langue maternelle est le portugais, mais je parle aussi français et luxembourgeois.',
  grond:'Nommer aussi les autres langues montre l’ouverture linguistique, très valorisée à l’oral.',
  vocab:['Mammesprooch (langue maternelle)','schwätzen (parler)'], pitfall:'Oublier de conjuguer schwätzen à la 1re personne (ech schwätzen, avec -en).'},
{id:'q004', cat:'virstellung', lb:'Wéi laang wunnt Dir schonn zu Lëtzebuerg?', fr:'Depuis combien de temps habitez-vous au Luxembourg ?',
  model_lb:'Ech wunnen elo scho fënnef Joer zu Lëtzebuerg.',
  model_fr:'J’habite déjà au Luxembourg depuis cinq ans.',
  grond:'« schonn » + durée marque bien l’idée de « déjà depuis ».',
  vocab:['wunnen (habiter)','schonn (déjà)'], pitfall:'Oublier zu devant le nom de la ville/pays.'},
{id:'q005', cat:'virstellung', lb:'Firwat wëllt Dir Lëtzebuerger Bierger ginn?', fr:'Pourquoi voulez-vous devenir citoyen luxembourgeois ?',
  model_lb:'Well ech hei schonn zanter Joren wunnen, schaffen a mech doheem fillen.',
  model_fr:'Parce que j’habite, je travaille et je me sens chez moi ici depuis des années.',
  grond:'Well introduit une raison ; le verbe passe en fin de proposition.',
  vocab:['well (parce que)','sech doheem fillen (se sentir chez soi)'], pitfall:'Laisser le verbe en 2e position après well (il doit reculer en fin de phrase).'},

// ── Famill ───────────────────────────────────────────────────────────────
{id:'q006', cat:'famill', lb:'Hutt Dir Kanner?', fr:'Avez-vous des enfants ?',
  model_lb:'Jo, ech hunn zwee Kanner, eng Meedchen a ee Jong.',
  model_fr:'Oui, j’ai deux enfants, une fille et un garçon.',
  grond:'Préciser le nombre et le genre donne une réponse riche, pas juste « jo ».',
  vocab:['Kand/Kanner (enfant/s)','Meedchen (fille)','Jong (garçon)'], pitfall:'Oublier l’accord eng/ee selon le genre.'},
{id:'q007', cat:'famill', lb:'Wéi vill Geschwëster hutt Dir?', fr:'Combien de frères et sœurs avez-vous ?',
  model_lb:'Ech hunn eng Schwëster an een Depôtbroder... nee, ee Brudder, en zéngt et sinn zwee zesummen.',
  model_fr:'J’ai une sœur et un frère, nous sommes deux au total.',
  grond:'Wéi vill + nom introduit toujours la quantité.',
  vocab:['Schwëster (sœur)','Brudder (frère)','Geschwëster (frères et sœurs)'], pitfall:'Confondre Brudder et Broder.'},
{id:'q008', cat:'famill', lb:'Wunnt Är Famill zu Lëtzebuerg?', fr:'Votre famille habite-t-elle au Luxembourg ?',
  model_lb:'Meng Fra a meng Kanner wunnen hei mat mir, meng Elteren wunnen nach am Ausland.',
  model_fr:'Ma femme et mes enfants habitent ici avec moi, mes parents vivent encore à l’étranger.',
  grond:'Contraster deux situations (ici / à l’étranger) montre une structure de phrase plus riche.',
  vocab:['Elteren (parents)','Ausland (étranger)'], pitfall:'Oublier de conjuguer wunnen au pluriel (wunnen, pas wunnt).'},
{id:'q009', cat:'famill', lb:'Wat mécht Äre Mann/Är Fra beruflech?', fr:'Que fait votre mari/femme comme métier ?',
  model_lb:'Mäi Mann schafft als Infirmier an engem Spidol hei zu Lëtzebuerg.',
  model_fr:'Mon mari travaille comme infirmier dans un hôpital ici au Luxembourg.',
  grond:'schaffen als + métier est la structure standard pour dire sa profession.',
  vocab:['schaffen als (travailler comme)','Spidol (hôpital)'], pitfall:'Oublier « als » avant le nom du métier.'},
{id:'q010', cat:'famill', lb:'Wéi oft gesitt Dir Är Famill?', fr:'À quelle fréquence voyez-vous votre famille ?',
  model_lb:'Ech gesinn meng Famill all Weekend, well si net wäit vun hei wunnen.',
  model_fr:'Je vois ma famille chaque week-end, car elle n’habite pas loin d’ici.',
  grond:'all + moment exprime la fréquence (all Weekend, all Woch, all Dag).',
  vocab:['all Weekend (chaque week-end)','wäit (loin)'], pitfall:'Utiliser jidderen au lieu de all pour la fréquence.'},

// ── Aarbecht ─────────────────────────────────────────────────────────────
{id:'q011', cat:'aarbecht', lb:'Wat ass Äre Beruff?', fr:'Quel est votre métier ?',
  model_lb:'Ech si Kach vu Beruff an ech schaffen an engem Restaurant an der Stad.',
  model_fr:'Je suis cuisinier de métier et je travaille dans un restaurant en ville.',
  grond:'vu Beruff après le métier précise « de métier », très naturel à l’oral.',
  vocab:['Beruff (métier)','Kach (cuisinier)'], pitfall:'Oublier l’article devant Restaurant.'},
{id:'q012', cat:'aarbecht', lb:'Wéi laang schafft Dir schonn do?', fr:'Depuis combien de temps travaillez-vous là-bas ?',
  model_lb:'Ech schaffen do scho véier Joer, virdrun hunn ech an enger Bäckerei geschafft.',
  model_fr:'J’y travaille depuis quatre ans, avant je travaillais dans une boulangerie.',
  grond:'virdrun + passé composé permet de contraster avec le présent.',
  vocab:['virdrun (avant)','Bäckerei (boulangerie)'], pitfall:'Mélanger le présent et le participe passé dans la même phrase.'},
{id:'q013', cat:'aarbecht', lb:'Wéi vill Deeg an der Woch schafft Dir?', fr:'Combien de jours par semaine travaillez-vous ?',
  model_lb:'Ech schaffen fënnef Deeg an der Woch, vu méindes bis freides.',
  model_fr:'Je travaille cinq jours par semaine, du lundi au vendredi.',
  grond:'vu … bis … donne une plage claire, utile pour tout horaire.',
  vocab:['Woch (semaine)','vu…bis (de…à)'], pitfall:'Dire an d’Woch au lieu de an der Woch.'},
{id:'q014', cat:'aarbecht', lb:'Gefält Iech Är Aarbecht?', fr:'Votre travail vous plaît-il ?',
  model_lb:'Jo, mir gefält meng Aarbecht immens gutt, well ech gär mat Leit schaffen.',
  model_fr:'Oui, mon travail me plaît beaucoup, parce que j’aime travailler avec des gens.',
  grond:'gefällt fonctionne à l’inverse du français : « mir gefält » = « ça me plaît ».',
  vocab:['gefalen (plaire)','gär hunn (aimer)'], pitfall:'Dire ech gefäll au lieu de mir gefält.'},
{id:'q015', cat:'aarbecht', lb:'Wéi kommt Dir op d’Aarbecht?', fr:'Comment allez-vous au travail ?',
  model_lb:'Ech fueren mam Bus op d’Aarbecht, dat dauert ongeféier eng hallef Stonn.',
  model_fr:'Je vais au travail en bus, ça dure environ une demi-heure.',
  grond:'mam + moyen de transport est la structure fixe (mam Bus, mam Auto, mam Vëlo).',
  vocab:['mam Bus (en bus)','ongeféier (environ)'], pitfall:'Oublier la contraction mam (mat + dem).'},
{id:'q016', cat:'aarbecht', lb:'Sidd Dir am Moment op der Sich no enger Aarbecht?', fr:'Cherchez-vous du travail en ce moment ?',
  model_lb:'Nee, ech hu scho eng Aarbecht, mä ech géing gär eng Formatioun maachen.',
  model_fr:'Non, j’ai déjà un travail, mais j’aimerais bien faire une formation.',
  grond:'géing gär + infinitif exprime un souhait poli, utile pour varier de wëllen.',
  vocab:['op der Sich sinn (être à la recherche)','Formatioun (formation)'], pitfall:'Confondre géing (conditionnel) avec ginn (devenir).'},

// ── Wunnen ───────────────────────────────────────────────────────────────
{id:'q017', cat:'wunnen', lb:'Wou wunnt Dir?', fr:'Où habitez-vous ?',
  model_lb:'Ech wunnen zu Esch, an engem rouege Quartier no bei der Gare.',
  model_fr:'J’habite à Esch, dans un quartier calme près de la gare.',
  grond:'Ajouter un détail (quartier, proximité) évite une réponse d’un seul mot.',
  vocab:['Quartier (quartier)','rouëg (calme)'], pitfall:'Oublier zu devant le nom de la localité.'},
{id:'q018', cat:'wunnen', lb:'Wunnt Dir an engem Haus oder an enger Wunneng?', fr:'Habitez-vous dans une maison ou un appartement ?',
  model_lb:'Ech wunnen an enger Wunneng mat zwee Schlofzëmmeren, am drëtte Stack.',
  model_fr:'J’habite dans un appartement avec deux chambres, au troisième étage.',
  grond:'oder pose un choix ; il faut reprendre l’option choisie dans la réponse, pas juste dire jo.',
  vocab:['Wunneng (appartement)','Stack (étage)'], pitfall:'Répondre « jo » à une question avec oder.'},
{id:'q019', cat:'wunnen', lb:'Zanter wéini wunnt Dir do?', fr:'Depuis quand habitez-vous là ?',
  model_lb:'Ech wunnen do zanter zwee Joer, virdrun hunn ech zu Diddeleng gewunnt.',
  model_fr:'J’y habite depuis deux ans, avant j’habitais à Dudelange.',
  grond:'zanter + durée pour dire « depuis », comme en français.',
  vocab:['zanter wéini (depuis quand)'], pitfall:'Confondre zanter (depuis) et bis (jusqu’à).'},
{id:'q020', cat:'wunnen', lb:'Wéi vill kascht Är Locatioun am Mount?', fr:'Combien coûte votre loyer par mois ?',
  model_lb:'Ech bezuelen ongeféier néng honnert Euro Loyer am Mount.',
  model_fr:'Je paie environ neuf cents euros de loyer par mois.',
  grond:'Donner un chiffre approximatif (ongeféier) reste naturel sans devoir être exact.',
  vocab:['Loyer (loyer)','bezuelen (payer)'], pitfall:'Oublier am Mount pour préciser la périodicité.'},
{id:'q021', cat:'wunnen', lb:'Wat gefält Iech un Ärem Quartier?', fr:'Qu’est-ce qui vous plaît dans votre quartier ?',
  model_lb:'Mir gefält, datt alles zu Fouss erreechbar ass: de Buttek, d’Schoul an d’Bushaltestell.',
  model_fr:'Ce qui me plaît, c’est que tout est accessible à pied : le magasin, l’école et l’arrêt de bus.',
  grond:'datt introduit une explication détaillée ; le verbe recule en fin de proposition, comme après well.',
  vocab:['zu Fouss (à pied)','erreechbar (accessible)'], pitfall:'Garder le verbe en 2e position après datt.'},

// ── Transport ────────────────────────────────────────────────────────────
{id:'q022', cat:'transport', lb:'Hutt Dir en Auto?', fr:'Avez-vous une voiture ?',
  model_lb:'Jo, ech hu en Auto, mä ech notzen och vill den ëffentlechen Transport.',
  model_fr:'Oui, j’ai une voiture, mais j’utilise aussi beaucoup les transports publics.',
  grond:'mä + une nuance montre qu’on ne se limite pas à un seul mode de transport.',
  vocab:['ëffentlechen Transport (transports publics)','notzen (utiliser)'], pitfall:'Oublier l’article en devant Auto.'},
{id:'q023', cat:'transport', lb:'Wéi kommt Dir an d’Stad?', fr:'Comment allez-vous en ville ?',
  model_lb:'Ech huelen den Zuch bis op d’Gare an dann de Bus, an et ass alles gratis zu Lëtzebuerg.',
  model_fr:'Je prends le train jusqu’à la gare puis le bus, et tout est gratuit au Luxembourg.',
  grond:'Rappeler que les transports publics sont gratuits est un point culturel apprécié.',
  vocab:['den Zuch huelen (prendre le train)','gratis (gratuit)'], pitfall:'Dire de Zuch au lieu de den Zuch (accusatif après huelen).'},
{id:'q024', cat:'transport', lb:'Fiert Dir gär Vëlo?', fr:'Aimez-vous faire du vélo ?',
  model_lb:'Jo, am Summer fueren ech oft mam Vëlo op d’Aarbecht, wann d’Wieder gutt ass.',
  model_fr:'Oui, en été je vais souvent au travail à vélo, quand le temps est beau.',
  grond:'wann introduit une condition ; là aussi le verbe part en fin de proposition.',
  vocab:['mam Vëlo fueren (faire du vélo)','Wieder (temps/météo)'], pitfall:'Oublier de reculer le verbe après wann.'},
{id:'q025', cat:'transport', lb:'Ass et einfach fir zu Lëtzebuerg ze parken?', fr:'Est-ce facile de se garer au Luxembourg ?',
  model_lb:'Nee, an der Stad ass et heiansdo schwiereg, ech sichen dacks laang no engem Parkplaz.',
  model_fr:'Non, en ville c’est parfois difficile, je cherche souvent longtemps une place de parking.',
  grond:'heiansdo / dacks nuancent une opinion négative pour rester poli et précis.',
  vocab:['schwiereg (difficile)','Parkplaz (place de parking)'], pitfall:'Répondre par un simple « nee » sans justification.'},

// ── Fräizäit ─────────────────────────────────────────────────────────────
{id:'q026', cat:'fraizeit', lb:'Wat maacht Dir gär an Ärer Fräizäit?', fr:'Que faites-vous pendant votre temps libre ?',
  model_lb:'An menger Fräizäit lieft ech gär, a moies ginn ech spadséieren am Bësch.',
  model_fr:'Pendant mon temps libre j’aime lire, et le matin je vais me promener en forêt.',
  grond:'gär + verbe à l’infinitif juste après est la construction standard pour dire un goût.',
  vocab:['gär hunn (aimer bien)','spadséieren goen (aller se promener)'], pitfall:'Placer gär trop loin du verbe qu’il modifie.'},
{id:'q027', cat:'fraizeit', lb:'Sidd Dir Member vun engem Veräin?', fr:'Êtes-vous membre d’une association/club ?',
  model_lb:'Jo, ech spillen zanter engem Joer Fussball an engem lokale Veräin.',
  model_fr:'Oui, je joue au foot depuis un an dans un club local.',
  grond:'zanter engem Joer précise la durée sans avoir besoin d’une phrase entière séparée.',
  vocab:['Veräin (association/club)','spillen (jouer)'], pitfall:'Confondre Veräin et Verain à l’écrit (double point).'},
{id:'q028', cat:'fraizeit', lb:'Wéi eng Musek héiert Dir gär?', fr:'Quel genre de musique aimez-vous écouter ?',
  model_lb:'Ech héieren gär Popmusek, mä heiansdo och portugisesch Musek mat menger Famill.',
  model_fr:'J’aime écouter de la pop, mais parfois aussi de la musique portugaise avec ma famille.',
  grond:'héieren gär (et non « lauschteren gär ») est l’usage courant à l’oral pour « aimer écouter ».',
  vocab:['Musek héieren (écouter de la musique)'], pitfall:'Utiliser lauschteren au lieu de héieren pour « écouter » de la musique.'},
{id:'q029', cat:'fraizeit', lb:'Wat maacht Dir mat Ären Frënn?', fr:'Que faites-vous avec vos amis ?',
  model_lb:'Mir treffen eis heiansdo fir zesumme koche oder e Kaffi ze drénken.',
  model_fr:'On se retrouve parfois pour cuisiner ensemble ou boire un café.',
  grond:'sech treffen (verbe réfléchi) est la formule naturelle pour « se retrouver ».',
  vocab:['sech treffen (se retrouver)','zesummen (ensemble)'], pitfall:'Oublier le pronom réfléchi eis.'},

// ── Gesondheet ───────────────────────────────────────────────────────────
{id:'q030', cat:'gesondheet', lb:'Wéi geet et Iech haut?', fr:'Comment allez-vous aujourd’hui ?',
  model_lb:'Et geet mir gutt, merci, an Iech?',
  model_fr:'Ça va bien, merci, et vous ?',
  grond:'Renvoyer la question (an Iech?) montre une vraie interaction, valorisée à l’oral.',
  vocab:['et geet mir gutt (je vais bien)'], pitfall:'Oublier de renvoyer la question à l’examinateur.'},
{id:'q031', cat:'gesondheet', lb:'Gitt Dir oft bei den Dokter?', fr:'Allez-vous souvent chez le médecin ?',
  model_lb:'Nee, net oft, just eemol am Joer fir eng Kontroll.',
  model_fr:'Non, pas souvent, juste une fois par an pour un contrôle.',
  grond:'eemol am Joer précise une fréquence exacte et facile à retenir.',
  vocab:['bei den Dokter goen (aller chez le médecin)','Kontroll (contrôle)'], pitfall:'Dire zum Dokter au lieu de bei den Dokter.'},
{id:'q032', cat:'gesondheet', lb:'Wat maacht Dir fir gesond ze bleiwen?', fr:'Que faites-vous pour rester en bonne santé ?',
  model_lb:'Ech probéieren all Dag ze spazéieren an net ze vill Kaffi ze drénken.',
  model_fr:'J’essaie de marcher tous les jours et de ne pas boire trop de café.',
  grond:'probéieren ze + infinitif introduit un effort ou une habitude qu’on essaie de tenir.',
  vocab:['probéieren (essayer)','gesond bleiwen (rester en bonne santé)'], pitfall:'Oublier ze devant l’infinitif après probéieren.'},

// ── Iessen ───────────────────────────────────────────────────────────────
{id:'q033', cat:'iessen', lb:'Wat iesst Dir gär?', fr:'Qu’aimez-vous manger ?',
  model_lb:'Ech ieren gär... nee, ech iessen gär Geméis a Fësch, mä ech hu gär och e Kniddel heiansdo.',
  model_fr:'J’aime manger des légumes et du poisson, mais j’aime bien aussi un Kniddel de temps en temps.',
  grond:'Citer un plat luxembourgeois (Kniddel, Judd mat Gaardebounen) montre un intérêt pour la culture locale.',
  vocab:['Geméis (légumes)','Kniddel (plat luxembourgeois à base de pâte)'], pitfall:'Conjuguer iessen en ieren par erreur (irrégulier : ech iessen, du iess, hie/si iesst).'},
{id:'q034', cat:'iessen', lb:'Kacht Dir gär?', fr:'Aimez-vous cuisiner ?',
  model_lb:'Jo, ech kachen all Owend fir meng Famill, dat gefält mir vill.',
  model_fr:'Oui, je cuisine tous les soirs pour ma famille, ça me plaît beaucoup.',
  grond:'all Owend précise une habitude régulière, plus riche que juste « jo, gär ».',
  vocab:['kachen (cuisiner)','all Owend (tous les soirs)'], pitfall:'Placer all après le verbe au lieu d’avant l’expression de temps.'},
{id:'q035', cat:'iessen', lb:'Geet Dir gär an de Restaurant?', fr:'Aimez-vous aller au restaurant ?',
  model_lb:'Jo, mir ginn heiansdo samschdes an en italienesche Restaurant.',
  model_fr:'Oui, on va parfois le samedi dans un restaurant italien.',
  grond:'samschdes (adverbe de jour habituel) évite de dire « am Samschdeg », plus lourd.',
  vocab:['an de Restaurant goen (aller au restaurant)'], pitfall:'Dire zum Restaurant au lieu de an de Restaurant.'},

// ── Lëtzebuerg ───────────────────────────────────────────────────────────
{id:'q036', cat:'letzebuerg', lb:'Wat gefält Iech um Lëtzebuerg?', fr:'Qu’est-ce qui vous plaît au Luxembourg ?',
  model_lb:'Mir gefält, datt et sécher ass an datt et esou vill verschidde Kulturen hei gëtt.',
  model_fr:'Ce qui me plaît, c’est que c’est sûr et qu’il y a tellement de cultures différentes ici.',
  grond:'Deux idées reliées par an montrent une réponse structurée, pas une liste sèche.',
  vocab:['sécher (sûr)','verschidde Kulturen (cultures différentes)'], pitfall:'Répondre uniquement « alles » sans développer.'},
{id:'q037', cat:'letzebuerg', lb:'Wéi eng Sprooche schwätzt Dir am Alldag?', fr:'Quelles langues parlez-vous au quotidien ?',
  model_lb:'Am Alldag schwätzen ech Franséisch op der Aarbecht an heiansdo Lëtzebuergesch mat Noperen.',
  model_fr:'Au quotidien je parle français au travail et parfois luxembourgeois avec des voisins.',
  grond:'Distinguer le contexte (aarbecht / mat Noperen) montre une vraie compréhension de l’usage des langues au Luxembourg.',
  vocab:['Alldag (quotidien)','Noper/Noperen (voisin/s)'], pitfall:'Oublier de préciser dans quel contexte on parle chaque langue.'},
{id:'q038', cat:'letzebuerg', lb:'Wéi eng Plazen zu Lëtzebuerg kennt Dir gutt?', fr:'Quels endroits du Luxembourg connaissez-vous bien ?',
  model_lb:'Ech kenne gutt d’Stad an och Iechternach, well ech do scho war spadséieren.',
  model_fr:'Je connais bien la ville et aussi Echternach, parce que j’y suis déjà allé me promener.',
  grond:'well justifie la connaissance d’un lieu par une expérience concrète.',
  vocab:['Plaz/Plazen (endroit/s)','kennen (connaître)'], pitfall:'Confondre kennen (connaître un lieu/une personne) et wëssen (savoir un fait).'},
{id:'q039', cat:'letzebuerg', lb:'Wat mécht Dir un engem Nationalfeierdag?', fr:'Que faites-vous le jour de la fête nationale ?',
  model_lb:'Ech kucke gär de Feierwierk den Owend virdrun mat menge Frënn.',
  model_fr:'J’aime regarder le feu d’artifice la veille au soir avec mes amis.',
  grond:'den Owend virdrun (la veille au soir) : la fête se célèbre le 22 juin, veille du 23.',
  vocab:['Feierwierk (feu d’artifice)','Nationalfeierdag (fête nationale)'], pitfall:'Confondre le 22 (célébrations) et le 23 juin (jour férié).'},

// ── Pläng ────────────────────────────────────────────────────────────────
{id:'q040', cat:'plaeng', lb:'Wat sinn Är Pläng fir d’Zukunft?', fr:'Quels sont vos projets pour l’avenir ?',
  model_lb:'Ech wéilt gär meng Lëtzebuergesch Kenntnisser verbesseren an eng Formatioun ufänken.',
  model_fr:'J’aimerais améliorer mes connaissances en luxembourgeois et commencer une formation.',
  grond:'wéilt gär + infinitif exprime un souhait futur de façon polie et A2-appropriée.',
  vocab:['Zukunft (avenir)','verbesseren (améliorer)'], pitfall:'Utiliser wëllen (vouloir direct) là où wéilt gär (souhait poli) sonne plus naturel.'},
{id:'q041', cat:'plaeng', lb:'Wou gesitt Dir Iech an fënnef Joer?', fr:'Où vous voyez-vous dans cinq ans ?',
  model_lb:'An fënnef Joer hoffen ech, nach ëmmer hei ze wunnen a schaffen.',
  model_fr:'Dans cinq ans j’espère habiter et travailler encore ici.',
  grond:'hoffen, ze + infinitif introduit un espoir concernant le futur.',
  vocab:['hoffen (espérer)','nach ëmmer (encore/toujours)'], pitfall:'Oublier ze avant l’infinitif après hoffen.'},
{id:'q042', cat:'plaeng', lb:'Wëllt Dir nach eng aner Sprooch léieren?', fr:'Voulez-vous apprendre encore une autre langue ?',
  model_lb:'Jo, ech géing gär mäin Däitsch verbesseren, well ech et nach net gutt genuch schwätzen.',
  model_fr:'Oui, j’aimerais améliorer mon allemand, car je ne le parle pas encore assez bien.',
  grond:'noch net … genuch nuance honnêtement un niveau, utile pour parler de ses lacunes.',
  vocab:['léieren (apprendre)','genuch (assez)'], pitfall:'Oublier not/net devant l’adjectif pour la négation.'},
];

// ── Scènes-photos (module de description) ──────────────────────────────
// 27 vraies photos, fournies par l'utilisateur — fichiers dans /photos.
// Les titres/vocabulaire ci-dessous sont des PROVISOIRES génériques
// (je ne peux pas garantir avoir correctement identifié chaque scène) :
// à corriger facilement, un objet par ligne, rien d'autre à toucher.
const PHOTOS = [
  {id:'p01', file:'photos/a.jpg',  title:'Foto 1',  fr:'Scène du quotidien 1',  vocab:[]},
  {id:'p02', file:'photos/b.jpg',  title:'Foto 2',  fr:'Scène du quotidien 2',  vocab:[]},
  {id:'p03', file:'photos/c.jpg',  title:'Foto 3',  fr:'Scène du quotidien 3',  vocab:[]},
  {id:'p04', file:'photos/d.jpg',  title:'Foto 4',  fr:'Scène du quotidien 4',  vocab:[]},
  {id:'p05', file:'photos/e.jpg',  title:'Foto 5',  fr:'Scène du quotidien 5',  vocab:[]},
  {id:'p06', file:'photos/f.jpg',  title:'Foto 6',  fr:'Scène du quotidien 6',  vocab:[]},
  {id:'p07', file:'photos/g.jpg',  title:'Foto 7',  fr:'Scène du quotidien 7',  vocab:[]},
  {id:'p08', file:'photos/h.jpg',  title:'Foto 8',  fr:'Scène du quotidien 8',  vocab:[]},
  {id:'p09', file:'photos/i.jpg',  title:'Foto 9',  fr:'Scène du quotidien 9',  vocab:[]},
  {id:'p10', file:'photos/j.jpg',  title:'Foto 10', fr:'Scène du quotidien 10', vocab:[]},
  {id:'p11', file:'photos/k.jpg',  title:'Foto 11', fr:'Scène du quotidien 11', vocab:[]},
  {id:'p12', file:'photos/l.jpg',  title:'Foto 12', fr:'Scène du quotidien 12', vocab:[]},
  {id:'p13', file:'photos/m.jpg',  title:'Foto 13', fr:'Scène du quotidien 13', vocab:[]},
  {id:'p14', file:'photos/n.jpg',  title:'Foto 14', fr:'Scène du quotidien 14', vocab:[]},
  {id:'p15', file:'photos/o.jpg',  title:'Foto 15', fr:'Scène du quotidien 15', vocab:[]},
  {id:'p16', file:'photos/p.jpg',  title:'Foto 16', fr:'Scène du quotidien 16', vocab:[]},
  {id:'p17', file:'photos/q.jpg',  title:'Foto 17', fr:'Scène du quotidien 17', vocab:[]},
  {id:'p18', file:'photos/r.jpg',  title:'Foto 18', fr:'Scène du quotidien 18', vocab:[]},
  {id:'p19', file:'photos/s.jpg',  title:'Foto 19', fr:'Scène du quotidien 19', vocab:[]},
  {id:'p20', file:'photos/t.jpg',  title:'Foto 20', fr:'Scène du quotidien 20', vocab:[]},
  {id:'p21', file:'photos/u.jpg',  title:'Foto 21', fr:'Scène du quotidien 21', vocab:[]},
  {id:'p22', file:'photos/v.jpg',  title:'Foto 22', fr:'Scène du quotidien 22', vocab:[]},
  {id:'p23', file:'photos/w.jpg',  title:'Foto 23', fr:'Scène du quotidien 23', vocab:[]},
  {id:'p24', file:'photos/x.jpg',  title:'Foto 24', fr:'Scène du quotidien 24', vocab:[]},
  {id:'p25', file:'photos/y.jpg',  title:'Foto 25', fr:'Scène du quotidien 25', vocab:[]},
  {id:'p26', file:'photos/z.jpg',  title:'Foto 26', fr:'Scène du quotidien 26', vocab:[]},
  {id:'p27', file:'photos/aa.jpg', title:'Foto 27', fr:'Scène du quotidien 27', vocab:[]},
];

global.CORPUS = {cats:CATS, questions:QUESTIONS, photos:PHOTOS};
})(window);
